### ISSUE TITLE
linux modify resolution crash

### ISSUE THREAD

**Issue by wang332127858** [smasherprog/screen_capture_lite#137]
#0  malloc_consolidate (av=av@entry=0x2af698000020) at malloc.c:4147
#1  0x00002af68a6be135 in _int_malloc (av=av@entry=0x2af698000020, bytes=bytes@entry=4680) at malloc.c:3444
#2  0x00002af68a6c2214 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3241
#3  0x00002af6869c9e6e in XOpenDisplay () from /lib64/libX11.so.6
#4  0x00000000005f75d1 in SL::Screen_Capture::GetMonitors() ()
#5  0x00000000005f6284 in SL::Screen_Capture::ThreadManager::Init(std::shared_ptr<SL::Screen_Capture::Thread_Data> const&) ()
#6  0x00000000005f30bc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}> > >::_M_run() ()
#7  0x000000000062abef in execute_native_thread_routine ()
#8  0x00002af68611eea5 in start_thread (arg=0x2af69689b700) at pthread_create.c:307
#9  0x00002af68a73a9fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by wang332127858** [comment]
#0  0x00002ac3627a3387 in raise () from /lib64/libc.so.6
#1  0x00002ac3627a4a78 in abort () from /lib64/libc.so.6
#2  0x00002ac361259a95 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00002ac361257a06 in ?? () from /lib64/libstdc++.so.6
#4  0x00002ac361257a33 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00002ac361257c53 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00002ac3612acf30 in std::__throw_system_error(int) () from /lib64/libstdc++.so.6
#7  0x00002ac3612ae0e8 in std::thread::join() () from /lib64/libstdc++.so.6
#8  0x00000000005deed3 in SL::Screen_Capture::ThreadManager::Join (this=0x2ac36e9cab70)
#9  0x00000000005d497d in SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}::operator()() const (__closure=0x3aca988)
#10 0x00000000005d69a1 in std::__invoke_impl<void, SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}>(std::__invoke_other, SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}&&) (__f=<unknown type in /apps/jhapp/bin/JHAppSession, CU 0x1197770, DIE 0x11d1fdb>)
#11 0x00000000005d5c7f in std::__invoke<SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}>(std::__invoke_result&&, (SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}&&)...) (__fn=<unknown type in /apps/jhapp/bin/JHAppSession, CU 0x1197770, DIE 0x11d3828>)
#12 0x00000000005db724 in std::thread::_Invoker<std::tuple<SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x3aca988) at /opt/rh/devtoolset-8/root/usr/include/c++/8/thread:244
#13 0x00000000005db602 in std::thread::_Invoker<std::tuple<SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}> >::operator()() (
    this=0x3aca988) at /opt/rh/devtoolset-8/root/usr/include/c++/8/thread:253
#14 0x00000000005db4e6 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<SL::Screen_Capture::ScreenCaptureManager::start()::{lambda()#1}> > >::_M_run() (this=0x3aca980) at /opt/rh/devtoolset-8/root/usr/include/c++/8/thread:196
#15 0x0000000000626d6f in execute_native_thread_routine ()
#16 0x00002ac35e039ea5 in start_thread () from /lib64/libpthread.so.0
#17 0x00002ac36286b96d in clone () from /lib64/libc.so.6
